#!/usr/bin/env sh

if [ ! -e "$HOME/.oh-my-emacs/.git/index" ]; then
    git clone https://github.com/damon-kwok/oh-my-emacs $HOME/.oh-my-emacs --depth=1
else
    cd $HOME/.oh-my-emacs
    git pull
fi

link-init-el() {
    tip "link"
    bkdir=~/conf-backup/`date +%Y-%m-%d@%H-%M-%S`
    mkdir -p $bkdir

    if [ -e ~/.emacs ]; then
	mv ~/.emacs $bkdir
    fi

    if [ -e ~/conf ]; then
	mv ~/conf $bkdir
    fi

    tip "link .emacs"
    cp -a $OME_ROOT/conf/init.el ~/.emacs 
    ln -s $OME_ROOT/conf ~/conf 
}
link-init-el
