#!/usr/bin/env bash

if [ ! -e "$HOME/.oh-my-emacs/.git/index" ]; then
    git clone git@github.com:damon-kwok/oh-my-emacs $HOME/.oh-my-emacs --depth=1
else
    cd $HOME/.oh-my-emacs
    git pull
fi

if [ ! -e "$HOME/workspace/.git/index" ]; then
    git clone git@gitlab.com:damon-kwok/workspace $HOME/workspace --depth=1
else
    cd $HOME/workspace
    git pull
fi

chmod +x $HOME/workspace/bin/*

grep "workspace/bin/env" $HOME/.bashrc >/dev/null
if [ $? -eq 0 ]; then	
    echo "found env!"
else
    echo "" >> ~/.bashrc
    echo "# oh-my-emacs" >> ~/.bashrc
    echo "source \$HOME/workspace/bin/env" >> $HOME/.bashrc
    echo "source \$HOME/workspace/bin/lib" >> $HOME/.bashrc
    echo "source \$HOME/workspace/bin/tool" >> $HOME/.bashrc
    echo "source \$HOME/workspace/bin/proj" >> $HOME/.bashrc
fi

grep "workspace/bin/env" $HOME/.profile >/dev/null
if [ $? -eq 0 ]; then	
    echo "found env!"
else
    echo "" >> ~/.profile
    echo "# oh-my-emacs" >> ~/.profile
    echo "source \$HOME/workspace/bin/env" >> $HOME/.profile
fi

function link-init-el() {
    echo "backup old emacs config"
    bkdir=~/emacs-config-backup/`date +%Y-%m-%d@%H-%M-%S`
    mkdir -p $bkdir

    if [ -e ~/.emacs ]; then
	mv ~/.emacs $bkdir
    fi

    if [ -e ~/emacs-config ]; then
	mv ~/emacs-config $bkdir
    fi

    echo "link .emacs"
    cp -a $HOME/.oh-my-emacs/emacs-config/init.el ~/.emacs 
    #ln -s $HOME/.oh-my-emacs/emacs-config ~/emacs-config 
}
link-init-el

source $HOME/.bashrc
