#!/usr/bin/env bash

function ${1:`(ome-bufname-no-ext)`}-install() {
    got-os-type
    case $OME_OS in
        # Linux
        $OS_DEBIAN) ;;
        $OS_UBUNTU) ;;
        $OS_REDHAT) ;;
        $OS_FEDORA) ;;
        $OS_GENTOO) ;;
        $OS_ARCH) ;;
        $OS_ALPINE) ;;
        $OS_VOID) ;;
        # Unix
        $OS_MACOS) ;;
        $OS_AIX) ;;
        $OS_SORLARIS) ;;
        $OS_FREEBSD) ;;
        $OS_OPENBSD) ;;
        # Windows
        $OS_CYGWIN) ;;
        $OS_MSYS2) ;;
        # Other
        $OS_UNKNOW) ;;
    esac
}

function $1-uninstall() {
    echo-error "'$1-uninstall' not implemented"
}

function $1-exist-p() {
    echo-error "'$1-exist-p' not implemented"
}
